CREATE TABLE IF NOT EXISTS users(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	address TEXT,
	city VARCHAR(100),
    state VARCHAR(100),
    zipcode VARCHAR(20),
	dob DATE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);